apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spotify-sync
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  source:
    repoURL: https://github.com/Accurate0/spotify-sync.git
    path: kubernetes
    kustomize:
      images:
        - spotify-sync=ghcr.io/accurate0/spotify-sync:${ARGOCD_APP_REVISION}
  destination:
    server: https://kubernetes.default.svc
    namespace: spotify-sync
operation:
  initiatedBy:
    username: github-actions
  sync:
    prune: true
    syncStrategy:
      hook: {}
