apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spotify-sync
  namespace: argocd
spec:
  ignoreDifferences:
    - group: "*"
      kind: Secret
      name: spotify-sync-managed-secrets
  syncPolicy:
    syncOptions:
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
  project: default
  source:
    repoURL: https://github.com/Accurate0/spotify-sync.git
    path: kubernetes
    directory:
      include: "*.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: spotify-sync
operation:
  initiatedBy:
    username: github-actions
  sync:
    prune: true
    syncStrategy:
      hook: {}
