apiVersion: v1
kind: Namespace
metadata:
  name: spotify-sync
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spotify-sync-ingress
  namespace: spotify-sync
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
    - host: spotify-sync.anurag.sh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spotify-sync-service
                port:
                  number: 80
  tls:
    - secretName: spotify-sync-anurag-sh-tls
      hosts:
        - spotify-sync.anurag.sh
---
apiVersion: v1
kind: Secret
metadata:
  name: spotify-sync-secrets
  namespace: spotify-sync
data:
  clientid: bXktYXBw
  clientsecret: Mzk1MjgkdmRnN0pi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spotify-sync-pvc
  namespace: spotify-sync
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-prod
  resources:
    requests:
      storage: 50Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spotify-sync-deploy
  namespace: spotify-sync
spec:
  selector:
    matchLabels:
      app: spotify-sync-app
  replicas: 1
  template:
    metadata:
      labels:
        app: spotify-sync-app
    spec:
      containers:
        - name: spotify-sync
          image: ghcr.io/accurate0/spotify-sync:latest
          volumeMounts:
            - name: spotify-sync-pvc
              mountPath: /data
          env:
            - name: SPOTIFYSYNC_REDIRECT_URI
              value: https://spotify-sync.anurag.sh

            - name: SPOTIFYSYNC_PLAYLIST_ID
              value: 0kjjqaH0XwOPC7Zbpg1qH7

            - name: SPOTIFYSYNC_DISCOVER_WEEKLY_ARCHIVE_PLAYLIST_ID
              value: 6aDvYxq7UzhsvaXdfceo5I

            - name: SPOTIFYSYNC_LIKED_SONGS_ARCHIVE_PLAYLIST_ID
              value: 3yXKGiVgZ9WYJxT3kkWDwp

            - name: SPOTIFYSYNC_CACHE_PATH
              value: /data/spotify.json

            - name: SPOTIFYSYNC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: spotify-sync-secrets
                  key: clientid

            - name: SPOTIFYSYNC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: spotify-sync-secrets
                  key: clientsecret
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: spotify-sync-service
  namespace: spotify-sync
spec:
  selector:
    app: spotify-sync-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
