apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spotify-sync
  namespace: spotify-sync
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-replicated
  resources:
    requests:
      storage: 50Mi
