apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spotify-sync
  namespace: spotify-sync
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-prod
  resources:
    requests:
      storage: 50Mi
