apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: spotify-sync-secret
  namespace: spotify-sync
spec:
  hostAPI: http://infisical-infisical-standalone-infisical.infisical.svc.cluster.local:8080/api
  resyncInterval: 10
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: spotify-sync-f-zuu
        envSlug: prod
        secretsPath: "/"
        recursive: true
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical

  managedSecretReference:
    secretName: spotify-sync-managed-secrets
    secretNamespace: spotify-sync
    creationPolicy: "Owner"
