name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    permissions:
      packages: write

    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/cache@v4
        with:
          path: app-target
          key: ${{ runner.os }}-app-target-${{ hashFiles('**/Cargo.lock') }}-spotify-sync

      - name: inject /app/target into docker
        uses: reproducible-containers/buildkit-cache-dance@v2.1.4
        with:
          cache-source: app-target
          cache-target: /app/spotify-sync-build/target/

      - uses: actions/cache@v4
        with:
          path: cargo-registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}-spotify-sync

      - name: inject /usr/local/cargo/registry/ into docker
        uses: reproducible-containers/buildkit-cache-dance@v2.1.4
        with:
          cache-source: cargo-registry
          cache-target: /usr/local/cargo/registry/

      - name: Docker build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/accurate0/spotify-sync:latest,ghcr.io/accurate0/spotify-sync:${{ github.sha }}
          build-args: |
            BINARY_NAME=spotify-sync
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      # This ugly bit is necessary if you don't want your cache to grow forever
      # till it hits GitHub's limit of 5GB.
      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          version: 1.76.6

      - name: Deploy to k8s
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
          ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_AUTH_TOKEN }}
          ARGOCD_SERVER: argocd.internal.anurag.sh
        run: |
          if [ ! -d "$HOME/.kube" ]; then
            mkdir -p $HOME/.kube
          fi

          echo -n "$KUBE_CONFIG" | base64 -di > $HOME/.kube/config

          kubectl -n spotify-sync create secret generic spotify-sync-secrets \
            --from-literal=clientid="${{ secrets.SPOTIFYSYNC_CLIENT_ID }}"  \
            --from-literal=clientsecret="${{ secrets.SPOTIFYSYNC_CLIENT_SECRET }}" \
            -o yaml --dry-run=client > secrets.yaml

          kubectl apply -f secrets.yaml application.yaml
