name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    permissions:
      packages: write

    uses: Accurate0/workflows/.github/workflows/build-push-docker.yaml@main
    with:
      directory: .
      image-name: spotify-sync
      docker-build-args: |
        BINARY_NAME=spotify-sync
      use-rust-caching: true

  deploy:
    needs: build
    uses: Accurate0/workflows/.github/workflows/deploy-app-k8s.yaml@main
    with:
      application-name: spotify-sync
    secrets:
      TS_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}
      TS_OAUTH_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
      ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_AUTH_TOKEN }}
